version: '3.8'
services:
  django-sample-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
volumes:
  docker-postgres: